// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUE2hnRED1sFlCs8-UGo9lw06RejVsFHM',
    appId: '1:664537471367:web:1dde97675e60493a581b22',
    messagingSenderId: '664537471367',
    projectId: 'watersmart-gh',
    authDomain: 'watersmart-gh.firebaseapp.com',
    storageBucket: 'watersmart-gh.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCceZedYH2SnLmh598VOrR7wGhRSIIfz0o',
    appId: '1:664537471367:ios:0672f6a7bcde555a581b22',
    messagingSenderId: '664537471367',
    projectId: 'watersmart-gh',
    storageBucket: 'watersmart-gh.appspot.com',
    iosBundleId: 'com.example.waterSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUE2hnRED1sFlCs8-UGo9lw06RejVsFHM',
    appId: '1:664537471367:web:5b45cced47fc6261581b22',
    messagingSenderId: '664537471367',
    projectId: 'watersmart-gh',
    authDomain: 'watersmart-gh.firebaseapp.com',
    storageBucket: 'watersmart-gh.appspot.com',
  );
}
